logging:
  level:
    org.springframework.security: TRACE
    com.example.andi.demo.*: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

spring.security:
  user.name: admin
  user.password: admin

server:
  error:
    whitelabel:
      enabled: false